# Generated by Django 4.2.13 on 2024-07-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbusinessmapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbusinessmapping',
            table='user_business_mapping',
        ),
    ]
