# Generated by Django 4.2.13 on 2024-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SUBSCRIPTION', 'SUBSCRIPTION')], max_length=15),
        ),
    ]
