# Generated by Django 4.2.13 on 2024-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_created_at_business_updated_at_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SUBSCRIPTION', 'SUBSCRIPTION')], max_length=18),
        ),
    ]
