# Generated by Django 4.2.13 on 2024-07-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_plan_subscriber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriber',
            table='subscription_subscribers',
        ),
    ]
