# Generated by Django 4.2.13 on 2024-07-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_plan_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
    ]
