# Generated by Django 4.2.13 on 2024-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
