# Generated by Django 4.2.13 on 2024-07-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_subscriber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.plan'),
        ),
    ]
