# Generated by Django 4.2.13 on 2024-07-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_subscriber_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.transaction'),
        ),
    ]
