# Generated by Django 4.2.13 on 2024-07-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_remove_transaction_subscriber_subscriber_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.plan'),
        ),
    ]
