# Generated by Django 4.2.13 on 2024-07-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_transaction_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='plan_end_date',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='plan_start_date',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='transaction',
        ),
    ]
